version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    steps:
      - run npm install

  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  version: 2
  build-test:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build-and-test
      - publish-stable:
          requires:
            - install
          filters:
            tags:
              only: /10.\d+.\d+(?!-\w+.\d)/
            branches:
              ignore: /.*/
      - publish-next:
          requires:
            - install
          filters:
            tags:
              only: /10.\d+.\d+(-\w+.\d)/
            branches:
              ignore: /.*/