version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install

  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run build

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm test
    
  publish-stable:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run deploy-stable

  publish-next:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run deploy-next
            
workflows:
  version: 2
  build-test:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - publish-stable:
          requires:
            - build
            - test
          filters:
            tags:
              only: /10.\d+.\d+(?!-\w+.\d)/
            branches:
              ignore: /.*/
      - publish-next:
          requires:
            - build
            - test
          filters:
            tags:
              only: /10\.0\.0-beta\./
            branches:
              ignore: /.*/
